### ISSUE TITLE
录屏功能没有做线程同步，会导致录制的视频偶现丢帧，出现花屏。

### ISSUE THREAD

**Issue by daishuqigood** [tencentyun/iot-ijkplayer#1]
录屏逻辑在read_thread线程实现，音频帧在audio_thread处理，视频帧在video_thread处理，录屏逻辑中会有AVPacket的拷贝，这个拷贝操作没有做线程同步，数据可能会在audio_thread和video_thread中free掉，导致合成的视频丢帧。

**Comment by tonychanchen** [comment]
这样free会crash的吧，另外花屏问题也可能是b帧存在，或者传输过程丢帧造成，建议先从这两方面排查下
